name: NodeJs Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.1
      - name: Install npm
        run: npm install
      - run: npm run build --if-present
      - name: Run test
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dummyproject

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dummyproject
